### PR TITLE
ICON UPDATE

### PR DESCRIPTION
**Pull request by bbwanjia**
made new icons for cpc
removed old icons
now 3 types of resolution are available in assets/ modified README files to fit icon filename
 Changes to be committed:
	modified:   README.md
	modified:   README_zh.md
	deleted:    assets/CPC4096.png
	deleted:    assets/CPC512.png
	new file:   assets/cpc-icon-high.png
	new file:   assets/cpc-icon-low.png
	new file:   assets/cpc-icon-mid.png

### CODE REVIEW

**Review by lightumcc — CHANGES_REQUESTED** [review]
CAIE是剑桥考试局的注册商标，我们不可以在Logo中使用这个单词

**Comment by lightumcc** [comment]
此文字颜色在Dark Mode下存在易读性问题

**Comment by iewnfod** [comment]
图标问题已经使用svg图像解决

**Comment by bbwanjia** [comment]
行吧

**Pull request closed without merging**
